// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// exported_utils.cpp
double logspace_add_c(const double x, const double y);
extern "C" SEXP _ernest_logspace_add_c(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(logspace_add_c(cpp11::as_cpp<cpp11::decay_t<const double>>(x), cpp11::as_cpp<cpp11::decay_t<const double>>(y)));
  END_CPP11
}
// exported_utils.cpp
cpp11::doubles get_points(cpp11::doubles log_lik, int init_nlive);
extern "C" SEXP _ernest_get_points(SEXP log_lik, SEXP init_nlive) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_points(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(log_lik), cpp11::as_cpp<cpp11::decay_t<int>>(init_nlive)));
  END_CPP11
}
// exported_utils.cpp
cpp11::doubles_matrix<cpp11::by_row> logspace_cumsum_mat(cpp11::doubles_matrix<cpp11::by_row> x);
extern "C" SEXP _ernest_logspace_cumsum_mat(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(logspace_cumsum_mat(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<cpp11::by_row>>>(x)));
  END_CPP11
}
// propose-impl.cpp
cpp11::list RandomWalkImpl(cpp11::doubles original, cpp11::function unit_log_fn, double criterion, unsigned int steps, double epsilon);
extern "C" SEXP _ernest_RandomWalkImpl(SEXP original, SEXP unit_log_fn, SEXP criterion, SEXP steps, SEXP epsilon) {
  BEGIN_CPP11
    return cpp11::as_sexp(RandomWalkImpl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(original), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(unit_log_fn), cpp11::as_cpp<cpp11::decay_t<double>>(criterion), cpp11::as_cpp<cpp11::decay_t<unsigned int>>(steps), cpp11::as_cpp<cpp11::decay_t<double>>(epsilon)));
  END_CPP11
}
// propose-impl.cpp
cpp11::list SliceImpl(cpp11::doubles original, cpp11::function unit_log_fn, double criterion, int steps, const int max_loop);
extern "C" SEXP _ernest_SliceImpl(SEXP original, SEXP unit_log_fn, SEXP criterion, SEXP steps, SEXP max_loop) {
  BEGIN_CPP11
    return cpp11::as_sexp(SliceImpl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(original), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(unit_log_fn), cpp11::as_cpp<cpp11::decay_t<double>>(criterion), cpp11::as_cpp<cpp11::decay_t<int>>(steps), cpp11::as_cpp<cpp11::decay_t<const int>>(max_loop)));
  END_CPP11
}
// update_lrps-impl.cpp
cpp11::list BoundingEllipsoid(cpp11::doubles_matrix<> X, double point_log_volume);
extern "C" SEXP _ernest_BoundingEllipsoid(SEXP X, SEXP point_log_volume) {
  BEGIN_CPP11
    return cpp11::as_sexp(BoundingEllipsoid(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(X), cpp11::as_cpp<cpp11::decay_t<double>>(point_log_volume)));
  END_CPP11
}
// update_lrps-impl.cpp
cpp11::list MultiBoundingEllipsoids(cpp11::doubles_matrix<> X, double point_log_volume);
extern "C" SEXP _ernest_MultiBoundingEllipsoids(SEXP X, SEXP point_log_volume) {
  BEGIN_CPP11
    return cpp11::as_sexp(MultiBoundingEllipsoids(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(X), cpp11::as_cpp<cpp11::decay_t<double>>(point_log_volume)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ernest_BoundingEllipsoid",       (DL_FUNC) &_ernest_BoundingEllipsoid,       2},
    {"_ernest_MultiBoundingEllipsoids", (DL_FUNC) &_ernest_MultiBoundingEllipsoids, 2},
    {"_ernest_RandomWalkImpl",          (DL_FUNC) &_ernest_RandomWalkImpl,          5},
    {"_ernest_SliceImpl",               (DL_FUNC) &_ernest_SliceImpl,               5},
    {"_ernest_get_points",              (DL_FUNC) &_ernest_get_points,              2},
    {"_ernest_logspace_add_c",          (DL_FUNC) &_ernest_logspace_add_c,          2},
    {"_ernest_logspace_cumsum_mat",     (DL_FUNC) &_ernest_logspace_cumsum_mat,     1},
    {"run_testthat_tests",              (DL_FUNC) &run_testthat_tests,              1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_ernest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
