// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// exported_utils.cpp
double logaddexp(double x, double y);
extern "C" SEXP _ernest_logaddexp(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(logaddexp(cpp11::as_cpp<cpp11::decay_t<double>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(y)));
  END_CPP11
}
// propose-impl.cpp
cpp11::list NURSImpl(cpp11::doubles original, cpp11::function unit_log_fn, double criterion, int steps, double h, int M);
extern "C" SEXP _ernest_NURSImpl(SEXP original, SEXP unit_log_fn, SEXP criterion, SEXP steps, SEXP h, SEXP M) {
  BEGIN_CPP11
    return cpp11::as_sexp(NURSImpl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(original), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(unit_log_fn), cpp11::as_cpp<cpp11::decay_t<double>>(criterion), cpp11::as_cpp<cpp11::decay_t<int>>(steps), cpp11::as_cpp<cpp11::decay_t<double>>(h), cpp11::as_cpp<cpp11::decay_t<int>>(M)));
  END_CPP11
}
// propose-impl.cpp
cpp11::list RandomWalkImpl(cpp11::doubles original, cpp11::function unit_log_fn, double criterion, int steps, double epsilon);
extern "C" SEXP _ernest_RandomWalkImpl(SEXP original, SEXP unit_log_fn, SEXP criterion, SEXP steps, SEXP epsilon) {
  BEGIN_CPP11
    return cpp11::as_sexp(RandomWalkImpl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(original), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(unit_log_fn), cpp11::as_cpp<cpp11::decay_t<double>>(criterion), cpp11::as_cpp<cpp11::decay_t<int>>(steps), cpp11::as_cpp<cpp11::decay_t<double>>(epsilon)));
  END_CPP11
}
// propose-impl.cpp
cpp11::list SliceImpl(cpp11::doubles original, cpp11::function unit_log_fn, double criterion, cpp11::doubles lower, cpp11::doubles upper, const int max_loop);
extern "C" SEXP _ernest_SliceImpl(SEXP original, SEXP unit_log_fn, SEXP criterion, SEXP lower, SEXP upper, SEXP max_loop) {
  BEGIN_CPP11
    return cpp11::as_sexp(SliceImpl(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(original), cpp11::as_cpp<cpp11::decay_t<cpp11::function>>(unit_log_fn), cpp11::as_cpp<cpp11::decay_t<double>>(criterion), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lower), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(upper), cpp11::as_cpp<cpp11::decay_t<const int>>(max_loop)));
  END_CPP11
}
// update_lrps-impl.cpp
cpp11::list BoundingEllipsoid(cpp11::doubles_matrix<> X);
extern "C" SEXP _ernest_BoundingEllipsoid(SEXP X) {
  BEGIN_CPP11
    return cpp11::as_sexp(BoundingEllipsoid(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(X)));
  END_CPP11
}
// update_lrps-impl.cpp
cpp11::list MultiBoundingEllipsoids(cpp11::doubles_matrix<> X, const double min_reduction, const bool allow_contact);
extern "C" SEXP _ernest_MultiBoundingEllipsoids(SEXP X, SEXP min_reduction, SEXP allow_contact) {
  BEGIN_CPP11
    return cpp11::as_sexp(MultiBoundingEllipsoids(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(X), cpp11::as_cpp<cpp11::decay_t<const double>>(min_reduction), cpp11::as_cpp<cpp11::decay_t<const bool>>(allow_contact)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP run_testthat_tests(void *);

static const R_CallMethodDef CallEntries[] = {
    {"_ernest_BoundingEllipsoid",       (DL_FUNC) &_ernest_BoundingEllipsoid,       1},
    {"_ernest_MultiBoundingEllipsoids", (DL_FUNC) &_ernest_MultiBoundingEllipsoids, 3},
    {"_ernest_NURSImpl",                (DL_FUNC) &_ernest_NURSImpl,                6},
    {"_ernest_RandomWalkImpl",          (DL_FUNC) &_ernest_RandomWalkImpl,          5},
    {"_ernest_SliceImpl",               (DL_FUNC) &_ernest_SliceImpl,               6},
    {"_ernest_logaddexp",               (DL_FUNC) &_ernest_logaddexp,               2},
    {"run_testthat_tests",              (DL_FUNC) &run_testthat_tests,              1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_ernest(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
