// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// propose_uniform_
Rcpp::List propose_uniform_(Rcpp::Function log_lik, Rcpp::Function prior_transform, int num_dim, double min_lik, int maxtry);
RcppExport SEXP _ernest_propose_uniform_(SEXP log_likSEXP, SEXP prior_transformSEXP, SEXP num_dimSEXP, SEXP min_likSEXP, SEXP maxtrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type log_lik(log_likSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prior_transform(prior_transformSEXP);
    Rcpp::traits::input_parameter< int >::type num_dim(num_dimSEXP);
    Rcpp::traits::input_parameter< double >::type min_lik(min_likSEXP);
    Rcpp::traits::input_parameter< int >::type maxtry(maxtrySEXP);
    rcpp_result_gen = Rcpp::wrap(propose_uniform_(log_lik, prior_transform, num_dim, min_lik, maxtry));
    return rcpp_result_gen;
END_RCPP
}
// propose_rwcube_
Rcpp::List propose_rwcube_(Rcpp::Function log_lik, Rcpp::Function prior_transform, Rcpp::NumericVector original, double min_lik, int max_steps, double epsilon);
RcppExport SEXP _ernest_propose_rwcube_(SEXP log_likSEXP, SEXP prior_transformSEXP, SEXP originalSEXP, SEXP min_likSEXP, SEXP max_stepsSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type log_lik(log_likSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type prior_transform(prior_transformSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type original(originalSEXP);
    Rcpp::traits::input_parameter< double >::type min_lik(min_likSEXP);
    Rcpp::traits::input_parameter< int >::type max_steps(max_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(propose_rwcube_(log_lik, prior_transform, original, min_lik, max_steps, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// logaddexp
double logaddexp(double x, double y);
RcppExport SEXP _ernest_logaddexp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(logaddexp(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ernest_propose_uniform_", (DL_FUNC) &_ernest_propose_uniform_, 5},
    {"_ernest_propose_rwcube_", (DL_FUNC) &_ernest_propose_rwcube_, 6},
    {"_ernest_logaddexp", (DL_FUNC) &_ernest_logaddexp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ernest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
