# Generated by cpp11: do not edit by hand

CubeImpl <- function(n_dim, unit_log_fn, criterion, max_loop) {
  .Call(`_ernest_CubeImpl`, n_dim, unit_log_fn, criterion, max_loop)
}

BoundingEllipsoid <- function(X) {
  .Call(`_ernest_BoundingEllipsoid`, X)
}

EllipsoidImpl <- function(unit_log_fn, criterion, scaledInvSqrtA, loc, max_loop) {
  .Call(`_ernest_EllipsoidImpl`, unit_log_fn, criterion, scaledInvSqrtA, loc, max_loop)
}

MultiBoundingEllipsoids <- function(X, min_reduction, min_distance) {
  .Call(`_ernest_MultiBoundingEllipsoids`, X, min_reduction, min_distance)
}

RandomWalkImpl <- function(original, unit_log_fn, criterion, steps, epsilon) {
  .Call(`_ernest_RandomWalkImpl`, original, unit_log_fn, criterion, steps, epsilon)
}

AdaptiveRWImpl <- function(original, unit_log_fn, criterion, steps, epsilon_init, epsilon_min, target_acceptance, mean, cov, strength, forgetfulness) {
  .Call(`_ernest_AdaptiveRWImpl`, original, unit_log_fn, criterion, steps, epsilon_init, epsilon_min, target_acceptance, mean, cov, strength, forgetfulness)
}

logaddexp <- function(x, y) {
  .Call(`_ernest_logaddexp`, x, y)
}
