# Generated by cpp11: do not edit by hand

AdaptiveRWImpl <- function(original, unit_log_fn, criterion, steps, epsilon, min_epsilon, target_acceptance, mean, covariance, strength, forgetfulness) {
  .Call(`_ernest_AdaptiveRWImpl`, original, unit_log_fn, criterion, steps, epsilon, min_epsilon, target_acceptance, mean, covariance, strength, forgetfulness)
}

CubeImpl <- function(n_dim, unit_log_fn, criterion, max_loop) {
  .Call(`_ernest_CubeImpl`, n_dim, unit_log_fn, criterion, max_loop)
}

EllipsoidImpl <- function(unit_log_fn, criterion, cov, loc, d2, max_loop) {
  .Call(`_ernest_EllipsoidImpl`, unit_log_fn, criterion, cov, loc, d2, max_loop)
}

RandomWalkImpl <- function(original, unit_log_fn, criterion, steps, epsilon) {
  .Call(`_ernest_RandomWalkImpl`, original, unit_log_fn, criterion, steps, epsilon)
}

logaddexp <- function(x, y) {
  .Call(`_ernest_logaddexp`, x, y)
}
