# Generated by cpp11: do not edit by hand

CubeImpl <- function(n_dim, unit_log_fn, criterion, max_loop) {
  .Call(`_ernest_CubeImpl`, n_dim, unit_log_fn, criterion, max_loop)
}

EllipsoidImpl <- function(unit_log_fn, criterion, axes, loc, max_loop) {
  .Call(`_ernest_EllipsoidImpl`, unit_log_fn, criterion, axes, loc, max_loop)
}

RandomWalkImpl <- function(original, log_lik_fn, criterion, steps, epsilon, chol_cov) {
  .Call(`_ernest_RandomWalkImpl`, original, log_lik_fn, criterion, steps, epsilon, chol_cov)
}

test_ellipsoid <- function(axes) {
  .Call(`_ernest_test_ellipsoid`, axes)
}

logaddexp <- function(x, y) {
  .Call(`_ernest_logaddexp`, x, y)
}
