#' @name ernest_sampling
#'
#' @title Likelihood-Restricted Prior Samplers (LRPS)
#' @description Set up a nested sampling run by specifying a likelihood-
#' restricted prior sampling method.
#'
#' @details
#' Nested sampling relies on generating independent live points from a
#' prior space that all satisfy some minimum likelihood value or restriction.
#' There are many ways to perform this likelihood restricted prior sampling,
#' but ernest currently offers two foundational examples: A simple region-based
#' sampler in `uniform_cube`, and a local-step algorithm in `rwmh_cube`.

#' @rdname lrps_call
#'
#' @description
#' `unif_cube()` is a region-based sampler, where points are generated by
#' sampling uniformly within the unit hypercube, returning a point when
#' a sampled point exceeds  from the prior under a likelihood constraint is to
#' sample randomly from the prior and reject the point if the likelihood
#' constraint is not fulfilled. This method is horribly inefficient in even
#' moderately-large dimensions, but is useful for testing and debugging.
#'
#' @export
unif_cube <- function() {
  new_ernest_sampling(
    parameters = list(),
    name = "Uniform Cube",
    class = uniform_lrps
  )
}

#' @rdname lrps_call
#'
#' @description
#' `rwmh_cube` is a MCMC-based sampler, where points are generated by
#' taking random steps within the unit hypercube. The step size is evolve over
#' a walk to target an acceptance rate of `0.5`.
#'
#' @param steps Number of steps to take when generating a proposal point.
#' @param target_acceptance Step-size parameter, adjusted over the course of a run.
#'
#' @export
rwmh_cube <- function(steps = 25L, target_acceptance = 0.5) {
  new_ernest_sampling(
    parameters = list(steps = steps, target_acceptance = target_acceptance),
    name = "Random Walk Cube",
    class = rwcube_lrps
  )
}

#' Construct a generic ernest_sampling object.
#'
#' @param parameters Named list of control parameters.
#' @param name Name of the sampler.
#' @param class Associated R6 class for the sampler.
#'
#' @noRd
new_ernest_sampling <- function(parameters, name, class) {
  structure(
    list(
      parameters = parameters,
      name = name,
      class = class
    ),
    class = "ernest_sampling"
  )
}
