#' Run nested sampling to estimate Bayesian evidence
#'
#' Executes the nested sampling algorithm, iteratively replacing the worst live
#' point with a new sample from a likelihood-restricted prior until a stopping
#' criterion is met.
#'
#' @param x [[ernest_sampler]] or [[ernest_run]]\cr A nested sampling
#' specification.
#' @inheritDotParams compile.ernest_run -object
#' @param max_iterations `[integer(1)]`\cr The maximum number of iterations to
#' perform. Optional; if `NULL` this criterion is ignored.
#' @param max_evaluations `[integer(1)]`\cr The maximum number of
#' likelihood function evaluations to perform. Optional; if `NULL` this
#' criterion is ignored.
#' @param min_logz `[double(1)]`\cr The minimum log-ratio between the
#' current estimated evidence and the remaining evidence. Must be non-negative;
#' if set to zero, this criterion is ignored.
#' @param show_progress `[logical(1)]`\cr If `TRUE`, displays a progress spinner
#' and iteration counter during sampling. Optional; if `NULL` the global option
#' `rlib_message_verbosity` is used to determine whether to show progress.
#'
#' @returns `[ernest_run]`
#'
#' A named list containing the results of the nested sampling run, which
#' contains `nsample = nlive + niter` samples from the prior distribution.
#' This list inherits from [ernest_sampler], and additionally contains:
#' * `niter`: `[integer(1)]` Number of iterations performed.
#' * `neval`: `[integer(1)]` Total number of likelihood function evaluations.
#' Note that it is possible for a single call to a likelihood function to
#' evaluate the likelihoods of multiple parameter samples.
#' * `log_evidence`: `[double(1)]` The log-evidence estimate.
#' * `log_evidence_err`: `[double(1)]` The standard error of the log-evidence
#' estimate, estimated from `information`.
#' * `information`: `[double(1)]` The estimated Kullback-Leibler divergence.
#' * `samples`: `[list]` The posterior samples ordered by their log-likelihood
#' values:
#'   * `original`: `[matrix(double(), nsample, ndim)]` The samples
#'   transformed to the parameter space.
#'   * `unit_cube`: `[matrix(double(), nsample, ndim)]` The samples in
#'   the unit hypercube.
#' * `weights`: `[list]` Additional information on the points generated by the
#'   run:
#'   * `id`: `[integer(nsample)]` The index of each point in the live set
#'   for each sample.
#'   * `evaluations`: `[integer(nsample)]` The number of likelihood
#'   evaluations needed to replace each point.
#'   * `log_weight`: `[double(nsample)]` The log-weight of each sample.
#'   * `imp_weight`: `[double(nsample)]` The normalized importance weight
#'   for each sample. This is given by normalizing `log_weight` with
#'   `log_evidence`, then applying `exp` to the result so the weights sum to
#'   one.
#'   * `log_lik`: `[double(nsample)]` The log-likelihood for each sample.
#'   * `birth_lik`: `[double(nsample)]` The log-likelihood of the point used
#'   to create each sample.
#'
#' @details
#' At least one of `max_iterations`, `max_evaluations`, or `min_logz`
#' must specify a valid stopping criterion. Setting `min_logz` to zero while
#' leaving `max_iterations` and `max_evaluations` at their defaults will
#' result in an error.
#'
#' If `x` is an `ernest_run` object, the stopping criteria are checked against
#' the current state of the run. An error is thrown if the stopping criteria
#' have already been satisfied by `x`.
#'
#' The `min_logz` parameter controls the relative tolerance for the remaining
#' evidence in the unexplored parameter space. Sampling stops when the estimated
#' remaining evidence is sufficiently small compared to the accumulated
#' evidence.
#'
#' @references Skilling, J. (2006). Nested Sampling for General Bayesian
#' Computation. Bayesian Analysis, 1(4), 833–859. \doi{10.1214/06-BA127}
#'
#' @srrstats {BS2.12} The `show_progress` indicator controls whether a simple
#' spinner bar is shown during sampling.
#' @srrstats {BS4.0} References the paper containing the sampling algorithm.
#'
#' @examples
#' prior <- create_uniform_prior(lower = c(-1, -1), upper = 1)
#' ll_fn <- function(x) -sum(x^2)
#' sampler <- ernest_sampler(ll_fn, prior, nlive = 100)
#' sampler
#'
#' # Stop sampling after a set number of iterations or likelihood calls.
#' generate(sampler, max_iterations = 100)
#'
#' # The final number of calls may exceed `max_evaluations`, as `generate`
#' # only checks the number of calls when removing a live point.
#' generate(sampler, max_evaluations = 2600)
#'
#' # Use the default stopping criteria
#' \dontrun{ generate(sampler) }
#' @aliases ernest_run
#' @export
generate.ernest_sampler <- function(
  x,
  max_iterations = NULL,
  max_evaluations = NULL,
  min_logz = 0.05,
  show_progress = NULL,
  ...
) {
  if (is.null(show_progress)) {
    show_progress <- getOption("rlib_message_verbosity", "default") != "quiet"
  }
  check_bool(show_progress)
  control <- get_run_control(
    x,
    max_iterations,
    max_evaluations,
    min_logz
  )
  x <- compile(x, ...)
  info <- get_sampler_info(x)

  results <- nested_sampling_impl(
    live_env = x$run_env,
    lrps = x$lrps,
    sampler_info = info,
    control = control,
    show_progress = show_progress
  )
  new_ernest_run(x, results)
}

#' @srrstats {BS2.8} Calling generate on an ernest_run will continue the run
#' from the last known live set.
#'
#' @rdname generate.ernest_sampler
#' @export
generate.ernest_run <- function(
  x,
  max_iterations = NULL,
  max_evaluations = NULL,
  min_logz = 0.05,
  show_progress = NULL,
  ...
) {
  if (is.null(show_progress)) {
    show_progress <- getOption("rlib_message_verbosity", "default") != "quiet"
  }
  check_bool(show_progress)
  x <- compile(x, ...)
  if (inherits_only(x, "ernest_sampler")) {
    return(generate(
      x,
      max_iterations = max_iterations,
      max_evaluations = max_evaluations,
      min_logz = min_logz,
      show_progress = show_progress
    ))
  }

  control <- get_run_control(
    x,
    max_iterations,
    max_evaluations,
    min_logz
  )
  info <- get_sampler_info(x)

  results <- nested_sampling_impl(
    live_env = x$run_env,
    lrps = x$lrps,
    sampler_info = info,
    control = control,
    show_progress = show_progress
  )
  new_ernest_run(x, results)
}

#' Generate and validate stopping criteria.
#'
#' @param x Object used for nested sampling.
#' @param max_iterations Maximum number of iterations to perform.
#' @param max_evaluations Maximum number of likelihood function evals.
#' @param min_logz Minimum log-ratio between current estimated evidence and
#' remaining evidence.
#' @param call Environment for error reporting.
#'
#' @return A named list containing `max_iterations`, `max_evaluations`,
#' `min_logz`, `last_criterion`, `log_z`, `log_vol`, `cur_iter`, and `cur_eval`.
#' @noRd
get_run_control <- function(
  x,
  max_iterations,
  max_evaluations,
  min_logz,
  call = caller_env()
) {
  check_number_whole(max_iterations, min = 1, allow_null = TRUE, call = call)
  check_number_whole(max_evaluations, min = 1, allow_null = TRUE, call = call)
  check_number_decimal(min_logz, min = 0, call = call)
  no_stopping <- identical(min_logz, 0) &&
    is.null(max_iterations) &&
    is.null(max_evaluations)
  if (no_stopping) {
    cli::cli_abort(
      c(
        "Can't perform nested sampling without any stopping criteria.",
        "i" = "Have you set either `max_iterations` or `max_evaluations`?"
      ),
      call = call
    )
  }

  max_iterations <- max_iterations %||% .Machine$integer.max
  max_evaluations <- max_evaluations %||% .Machine$integer.max

  if (inherits_only(x, "ernest_sampler")) {
    return(list(
      max_iterations = as.integer(max_iterations),
      max_evaluations = as.integer(max_evaluations),
      min_logz = as.double(min_logz),
      last_criterion = -1e300,
      log_vol = 0,
      log_z = -1e300,
      cur_iter = 0L,
      cur_eval = 0L
    ))
  }

  cur_iter <- x$niter
  cur_eval <- x$neval
  prev_integration <- compute_integral(
    x$weights$log_lik,
    get_log_vol(x$nlive, niter = cur_iter)
  )
  last_criterion <- prev_integration$log_lik[cur_iter]
  log_z <- prev_integration$log_evidence[cur_iter]
  log_vol <- prev_integration$log_vol[cur_iter]
  max_lik <- max(env_get(x$run_env, "log_lik"))
  d_logz <- logspace_add_c(0, max_lik + log_vol - log_z)

  if (cur_iter >= max_iterations) {
    cli::cli_abort(
      c(
        "`max_iterations` must be strictly larger than {cur_iter}.",
        "x" = "`x` already contains previously-generated samples.",
        "i" = "Should you use `clear` to erase previous samples from `x`?"
      ),
      call = call
    )
  }
  if (cur_eval >= max_evaluations) {
    cli::cli_abort(
      c(
        "`max_evaluations` must be strictly larger than {cur_eval}.",
        "x" = "`x` already contains previously-generated samples.",
        "i" = "Should you use `clear` to erase previous samples from `x`?"
      ),
      call = call
    )
  }
  if (min_logz >= d_logz) {
    cli::cli_abort(
      c(
        "`min_logz` must be strictly smaller than {round(d_logz, digits = 3)}.",
        "x" = "`x` already contains previously-generated samples.",
        "i" = "Should you use `clear` to erase previous samples from `x`?"
      ),
      call = call
    )
  }

  list(
    max_iterations = as.integer(max_iterations),
    max_evaluations = as.integer(max_evaluations),
    min_logz = as.double(min_logz),
    last_criterion = last_criterion,
    log_vol = log_vol,
    log_z = log_z,
    cur_iter = as.integer(cur_iter),
    cur_eval = as.integer(cur_eval)
  )
}

#' Extract sampler information for use in nested sampling.
#'
#' @param x An `ernest_sampler` or `ernest_run` object.
#' @return A named list containing `seed`, `nlive`, `first_update`,
#' and `update_interval`.
#' @noRd
get_sampler_info <- function(x) {
  list(
    seed = attr(x, "seed"),
    nlive = x$nlive,
    first_update = x$first_update,
    update_interval = x$update_interval
  )
}
