#' @name lrps
#'
#' @title Likelihood-Restricted Prior Samplers (LRPS)
#' @description Set up a nested sampling run by specifying a likelihood-
#' restricted prior sampling method.
#'
#' @details
#' Nested sampling relies on generating independent live points from a
#' prior space that all satisfy some minimum likelihood value or restriction.
#' There are many ways to perform this likelihood restricted prior sampling,
#' but ernest currently offers two foundational examples: A simple region-based
#' sampler in `uniform_cube`, and a local-step algorithm in `rwmh_cube`.
#'
#' @param max_loop The maximum number of calls to the likelihood function a
#' sampler will make when trying to propose a new point given one likelihood
#' constraint. Once exceeded, ernest will abort and report an error to the user.
#' If non-null, this overwrites the `ernest.max_loop` global option
#' (default `1e6L`).
#'
#' @return an `ErnestLRPS` object that can be passed to [nested_sampling()]
NULL

#' @rdname lrps
#'
#' @description
#' `uniform_cube()` is a region-based sampler, where points are generated by
#' sampling uniformly within the unit hypercube, returning a point when
#' a sampled point exceeds  from the prior under a likelihood constraint is to
#' sample randomly from the prior and reject the point if the likelihood
#' constraint is not fulfilled. This method is horribly inefficient in even
#' moderately-large dimensions, but is useful for testing and debugging.
#'
#' @export
unif_cube <- function(max_loop = NULL) {
  check_number_whole(max_loop, min = 1, allow_null = TRUE, allow_infinite = FALSE)
  structure(
    list(
      max_loop = max_loop
    ),
    class = c("unif_cube", "ernest_lrps")
  )
}

#' @rdname lrps
#'
#' @description
#' `rwmh_cube` is a region-based sampler, where points are generated by
#' taking random steps within the unit hypercube. The step size is evolve over
#' a walk to target an acceptance rate of `0.5`.
#'
#' @param epsilon step-size hyperparameter, defaults to `0.1`.
#' @param steps minimum number of steps to take, defaults to `20`.
#'
#' @export
rwmh_cube <- function(epsilon = 0.1, steps = 20L, max_loop = NULL) {
  if (epsilon <= 0) {
    cli::cli_abort("`epsilon` must be a number larger than 0, not {epsilon}")
  }
  check_number_decimal(epsilon, allow_infinite = FALSE)
  check_number_whole(steps, min = 1, allow_infinite = FALSE)
  structure(
    list(
      epsilon = epsilon,
      steps = as.integer(steps),
      max_loop = max_loop
    ),
    class = c("rwmh_cube", "ernest_lrps")
  )
}

#' Build a nested sampler with an `lrps_sampler` object.
#'
#' Dispatches over `lrps_sampler` to build an `ErnestSampler` object.
#'
#' @inheritParams nested_sampling
#'
#' @returns An `ErnestSampler` object.
#' @keywords internal
#' @noRd
build_sampler <- function(sampler, ...) {
  UseMethod("build_sampler")
}

#' @rdname build_sampler
#' @export
#' @noRd
build_sampler.unif_cube <- function(sampler, log_lik, prior_transform,
                                    n_dim, n_points,
                                    first_update, between_update, verbose,
                                    ...) {
  new_uniform_cube(
    log_lik = log_lik,
    prior_transform = prior_transform,
    n_dim = n_dim,
    n_points = n_points,
    first_update = first_update,
    between_update = between_update,
    verbose = verbose,
    wrk = NULL
  )
}

#' @rdname build_sampler
#' @export
#' @noRd
build_sampler.rwmh_cube <- function(sampler, log_lik, prior_transform,
                                    n_dim, n_points, first_update,
                                    between_update, verbose, ...) {
  new_rwmh_cube(
    log_lik = log_lik,
    prior_transform = prior_transform,
    n_dim = n_dim,
    n_points = n_points,
    first_update = first_update,
    between_update = between_update,
    verbose = verbose,
    steps = sampler$steps,
    epsilon = sampler$epsilon,
    wrk = NULL
  )
}
