#' Plot diagnostics for a nested sampling run
#'
#' Shows the normalised likelihood, importance weights, and evidence as
#' functions of log-volume.
#'
#' @param x An [ernest_estimate] or [ernest_run] object.
#' @inheritParams rlang::args_dots_empty
#'
#' @returns
#' Invisibly returns `x`. A `ggplot2::ggplot()` object is printed as a
#' side effect.
#'
#' The plot is faceted into three panels. The horizontal axis shows log-volume:
#' If `x` is an `ernest_run`, these estimates are derived from the run;
#' if `x` is an `ernest_estimate` (or `ndraws != 0`), these values are
#' simulated.
#'
#' The three `y` axes are:
#'
#' * **Evidence:** Estimate with an error ribbon drawn from either
#'   the estimated standard error (if `ernest_run`) or from the median credible
#'   interval (MCI) (if `ernest_estimate`);
#' * **Normalised Likelihood:** The likelihood value of the criteria used
#'   to draw new points from the likelihood-restricted prior sampler, normalised
#'   by the maximum likelihood generated during the run;
#' * **Posterior Weight:** The density of the posterior weights attributed to
#'   regions of volume within the prior. For `ernest_estimate` objects,
#'   an error ribbon is drawn with the MCI of this estimate.
#'
#' @note For `ernest_estimate`, `ndraws` should be large enough to plot the
#'
#' @srrstats {BS6.1} Default plot for return object.
#'
#' @seealso
#' * [calculate()] for generating `ernest_estimate` objects.
#' * [visualize()] for plotting the posterior distributions generated by a run.
#'
#' @rdname plot.ernest
#' @export
#' @examples
#' # Plot integration results from a run.
#' data(example_run)
#' plot(example_run)
#'
#' # Simulate results before plotting.
#' plot(example_run, ndraws = 50)
plot.ernest_estimate <- function(x, ...) {
  check_dots_empty()
  print(autoplot(x, ...))
}

#' @inheritParams calculate.ernest_run
#'
#' @rdname plot.ernest
#' @export
#' @examples
#' # Simulate results from a run, then plot simulated results.
#' sim <- calculate(example_run, ndraws = 50)
#' plot(sim)
plot.ernest_run <- function(x, ..., ndraws = 0) {
  check_dots_empty()
  check_number_whole(ndraws, lower = 0)
  if (ndraws != 0) {
    x <- calculate(x, ndraws = ndraws)
  }
  print(autoplot(x, ...))
}

# AUTOPLOT METHODS -----

#' Autoplot for Ernest Estimates
#'
#' Generates a ggplot object for an `ernest_estimate` object containing
#' uncertainty simulations.
#'
#' @param object An `ernest_estimate` object containing uncertainty simulations.
#' @param ... Additional arguments passed to the method.
#'
#' @return A ggplot object.
#' @noRd
#' @importFrom ggplot2 autoplot
#' @export
autoplot.ernest_estimate <- function(object, ...) {
  check_dots_empty()
  plot_tbl <- calc_hdi_tbl(object)
  autoplot_run_(
    plot_tbl$df,
    fill_name = plot_tbl$fill_name,
    fill_limits = plot_tbl$fill_limits,
    fill_labels = plot_tbl$fill_labels
  )
}

#' Autoplot for Ernest Run Objects
#'
#' Generates a ggplot object for an `ernest_run` object containing a nested
#' sampling run.
#'
#' @param object An `ernest_run` object containing a nested sampling run.
#' @param ... Additional arguments passed to the method.
#'
#' @return A ggplot object.
#' @noRd
#' @export
autoplot.ernest_run <- function(object, ...) {
  check_dots_empty()
  plot_tbl <- calc_var_tbl(
    log_volume = object$log_volume,
    log_evidence = object$log_evidence,
    log_evidence_var = object$log_evidence_var,
    log_weight = object$log_weight,
    log_lik = object$log_lik
  )
  autoplot_run_(
    plot_tbl$df,
    fill_name = plot_tbl$fill_name,
    fill_limits = plot_tbl$fill_limits,
    fill_labels = plot_tbl$fill_labels
  )
}

#' Calculate a data.frame for plotting evidence simulations
#'
#' Computes a data frame and metadata for plotting HDI-based uncertainty from
#' an `ernest_estimate` object.
#'
#' @param object An `ernest_estimate` object containing uncertainty simulations.
#'
#' @return A list containing a data frame for plotting and additional metadata
#' for the fill aesthetic. If HDI calculation fails, a warning is issued and a
#' fallback data frame with variance estimates is returned instead.
#' @noRd
calc_hdi_tbl <- function(object) {
  if (attr(object, "ndraws") < 100) {
    cli::cli_warn(
      "`ndraws` should be above 100 to accurately plot credible intervals."
    )
  }
  max_log_z <- tail(object$log_evidence, 1)
  w <- exp(object$log_weight - max_log_z)
  density_draws <- get_density(object$log_volume, w)
  log_volume <- density_draws$log_volume

  w_68 <- hdci(density_draws$density, width = 0.68)
  w_95 <- hdci(density_draws$density, width = 0.95)
  df_w <- vctrs::vec_rbind(w_68, w_95)
  df_w$log_vol <- rep(log_volume, 2)
  df_w$.label <- "Posterior Weight"

  rvar_evid <- interpolate_evidence(
    object$log_volume,
    object$log_evidence,
    log_volume
  )

  z_68 <- hdci(rvar_evid, width = 0.68)
  z_95 <- hdci(rvar_evid, width = 0.95)
  df_z <- vctrs::vec_rbind(z_68, z_95)
  df_z$log_vol <- rep(log_volume, 2)
  df_z$.label <- "Evidence"

  log_lik <- drop(posterior::draws_of(object$log_lik))
  df_ll <- data.frame(
    "log_vol" = mean(object$log_volume),
    ".label" = "Normalized Likelihood",
    ".var" = exp(log_lik - max(log_lik)),
    ".lower" = NA,
    ".upper" = NA,
    ".width" = NA
  )

  list(
    df = vctrs::vec_c(df_w, df_ll, df_z),
    "fill_name" = "MCI",
    "fill_limits" = c(0.95, 0.68),
    "fill_labels" = c("95%", "68%")
  )
}

#' Calculate a data.frame for plotting evidence values from a run
#'
#' Computes a data frame and metadata for plotting evidence, weights, and
#' likelihood from a nested sampling run.
#'
#' @param log_volume A numeric vector of log volume values.
#' @param log_evidence A numeric vector of log-evidence values.
#' @param log_evidence_var A numeric vector of log-evidence variances.
#' @param log_weight A numeric vector of log weights.
#' @param log_lik A numeric vector of log-likelihood values.
#'
#' @return A list containing a data frame for plotting and additional metadata
#' for the fill aesthetic.
#' @noRd
calc_var_tbl <- function(
  log_volume,
  log_evidence,
  log_evidence_var,
  log_weight,
  log_lik
) {
  df_z <- data.frame(
    "log_vol" = rep(log_volume, 3),
    ".label" = "Evidence",
    ".var" = rep(log_evidence, 3),
    ".width" = rep(c(1, 2, 3), each = length(log_volume)),
    ".err" = rep(sqrt(log_evidence_var), 3)
  )
  df_z[".lower"] <- exp(df_z$.var - (df_z$.width * df_z$.err))
  df_z[".upper"] <- exp(df_z$.var + (df_z$.width * df_z$.err))
  df_z$.var <- exp(df_z$.var)
  df_z$.err <- NULL

  max_log_z <- tail(log_evidence, 1)
  df_w <- data.frame(
    "log_vol" = log_volume,
    ".label" = "Posterior Weight",
    ".var" = exp(log_weight - max_log_z),
    ".lower" = NA,
    ".upper" = NA,
    ".width" = NA
  )
  df_ll <- data.frame(
    "log_vol" = log_volume,
    ".label" = "Normalized Likelihood",
    ".var" = exp(log_lik - max(log_lik)),
    ".lower" = NA,
    ".upper" = NA,
    ".width" = NA
  )
  list(
    "df" = vctrs::vec_c(df_w, df_ll, df_z),
    "fill_name" = expression(hat(sigma[Z])),
    "fill_limits" = c(3, 2, 1),
    "fill_labels" = c(
      expression(3 * sigma),
      expression(2 * sigma),
      expression(1 * sigma)
    )
  )
}

#' Autoplot helper for diagnostic plots
#'
#' Generates a ggplot object representing diagnostic plots for evidence,
#' weights, and likelihood.
#'
#' @param df A data.frame containing the plotting data.
#' @param fill_name Name of the fill aesthetic in the plot.
#' @param fill_limits Limits for the fill aesthetic.
#' @param fill_labels Labels for the fill aesthetic.
#'
#' @return A ggplot object representing the diagnostic plots.
#' @noRd
autoplot_run_ <- function(df, fill_name, fill_limits, fill_labels) {
  df$.width <- factor(
    as.character(df$.width),
    levels = as.character(fill_limits)
  )

  weight_ribbon <- any(!is.na(df$.width) & df$.label == "Posterior Weight")
  weight_geom <- if (weight_ribbon) {
    ggplot2::geom_ribbon(
      data = subset(df, df$.label == "Posterior Weight"),
      ggplot2::aes(
        ymin = .data[[".lower"]],
        ymax = .data[[".upper"]],
        fill = .data[[".width"]]
      ),
      alpha = 0.7
    )
  } else {
    ggplot2::geom_line(
      data = ~ subset(., df$.label == "Posterior Weight"),
      position = "identity"
    )
  }

  ggplot2::ggplot(
    df,
    ggplot2::aes(x = .data[["log_vol"]], y = .data[[".var"]])
  ) +
    ggplot2::geom_ribbon(
      data = ~ subset(., df$.label == "Evidence"),
      ggplot2::aes(
        ymin = .data[[".lower"]],
        ymax = .data[[".upper"]],
        fill = .data[[".width"]]
      ),
      alpha = 0.7
    ) +
    ggplot2::geom_line(
      data = ~ subset(., df$.label == "Evidence")
    ) +
    ggplot2::geom_line(
      data = ~ subset(., df$.label == "Normalized Likelihood")
    ) +
    ggplot2::geom_line(
      data = ~ subset(., df$.label == "Posterior Weight"),
      position = "identity"
    ) +
    weight_geom +
    ggplot2::scale_x_continuous("Log Volume") +
    ggplot2::scale_y_continuous(NULL) +
    ggplot2::scale_fill_viridis_d(
      fill_name,
      limits = factor(fill_limits),
      labels = fill_labels,
      direction = 1
    ) +
    ggplot2::facet_grid(
      rows = ggplot2::vars(.data[[".label"]]),
      scales = "free_y"
    ) +
    ggplot2::theme_classic()
}
