#' Plot diagnostics from nested sampling results
#'
#' Visualizes key diagnostics from nested sampling outputs, including the
#' normalized likelihood, posterior weights, and evidence as functions of
#' log-prior volume.
#'
#' @param x [[ernest_run]] or [[ernest_estimate]]\cr An object containing
#' results from nested sampling.
#' @param which `[character()]`\cr Choose which plots to display. Must be one
#' or more of `"evidence"`, `"weight"`, and `"likelihood"`.
#' @inheritParams rlang::args_dots_empty
#'
#' @returns `[invisible(x)]`. A `ggplot2::ggplot()` object is printed as a
#' side effect.
#'
#' @details
#' The plotting methods are structured around internal `autoplot_*` helpers
#' (`autoplot_evidence()`, `autoplot_weight()`, and `autoplot_likelihood()`).
#' Use `which` to select one or more diagnostics:
#'
#' * `which = "evidence"`: Plots the estimated marginal
#' likelihood (evidence) as a function of log-prior volume, with uncertainty
#' intervals. Peaks in this plot indicate regions of prior volume that
#' contribute most to the evidence estimate.
#' * `which = "weight"`: Shows the distribution of
#' posterior mass across log-prior volume. This plot highlights which regions
#' of the prior volume contain the most posterior probability, helping to
#' identify where the sampler concentrated its effort.
#' * `which = "likelihood"`: Displays the normalized
#' likelihood as a function of log-prior volume. Smoothness in this plot
#' indicates effective likelihood-restricted prior sampling, while
#' irregularities may suggest sampling difficulties or, in some cases,
#' misspecified likelihood functions.
#'
#' If `x` is an `ernest_run`, plotting uses deterministic integral estimates
#' (`calculate(x, ndraws = 0)`). For `which = "evidence"`, uncertainty bands
#' are derived from the analytic standard error stored in
#' `x$log_evidence_err`.
#'
#' If `x` is an `ernest_estimate` (or if `ndraws` is specified), the plots
#' are based on simulated log-volume trajectories. In this case,
#' `plot.ernest_estimate()` requires `attr(x, "ndraws") > 1`. Uncertainty for
#' `evidence` and `weight` is summarized using `ggdist` interval helpers
#' (`point_interval()` and `curve_interval()`) over interpolated curves.
#'
#' @note
#' Plotting multiple diagnostics with `which` requires \CRANpkg{patchwork}.
#' Plotting `evidence` or `weight` diagnostics requires \CRANpkg{ggdist}.
#'
#' @srrstats {BS6.1} Default plot for return object.
#'
#' @seealso
#' * [calculate()] for generating `ernest_estimate` objects.
#' * [visualize()] for plotting the posterior distributions generated by a run.
#'
#' @examples
#' # Plot results from a run.
#' data(example_run)
#' plot(example_run)
#'
#' # Simulate results before plotting.
#' set.seed(42)
#' plot(example_run, ndraws = 100)
#'
#' # Equivalently, simulate results, then plot:
#' set.seed(123)
#' est <- calculate(example_run, ndraws = 100)
#' plot(est)
#' @rdname plot.ernest_run
#' @export
plot.ernest_estimate <- function(
  x,
  which = c("evidence", "weight", "likelihood"),
  ...
) {
  check_dots_empty()
  which <- check_plot_which(which)
  print(autoplot(x, which, ...)) # nocov
}

#' @rdname plot.ernest_estimate
#' @export
plot.ernest_run <- function(
  x,
  which = c("evidence", "weight", "likelihood"),
  ...
) {
  which <- check_plot_which(which)
  withr::with_preserve_seed(
    obj <- calculate(x, ndraws = 0)
  )
  print(autoplot(obj, which, ...))
}

#' @rdname plot.ernest
#' @export
summary.ernest_estimate <- function(
  object,
  which = c("evidence", "weight", "likelihood"),
  n = 512,
  ...
) {
  check_dots_empty()
  which <- arg_match(which, multiple = TRUE)
  check_number_whole(n, min = 2)

  if (any(c("evidence", "weight") %in% which)) {
    check_installed("ggdist", "to summarize evidence and weight diagnostics")
  }

  log_volume <- posterior::draws_of(object$log_volume)
  log_evidence <- posterior::draws_of(object$log_evidence)
  log_weight <- posterior::draws_of(object$log_weight)
  weight <- if (nrow(log_weight) == 1) {
    log_z <- matrixStats::logSumExp(drop(log_weight))
    exp(log_weight - log_z)
  } else {
    exp(sweep(
      log_weight,
      1,
      log_evidence[, ncol(log_evidence)],
      FUN = "-"
    ))
  }

  lik <- exp(object$log_lik - max(object$log_lik))
  vol_rng <- ggdist::density_bounded(
    log_volume,
    bounds = c(NA, 0),
    range_only = TRUE
  )$x
  knots <- seq(vol_rng[1], vol_rng[2], length.out = n)
  print(length(knots))

  safe_curve <- \(x, y) {
    if (!is.matrix(drop(y))) {
      vctrs::data_frame(
        "x" = x,
        ".value" = y
      )
    } else {
      ggdist::curve_interval(
        vctrs::data_frame(
          "x" = x,
          ".value" = posterior::rvar(t(y))
        ),
        .along = x,
        .width = ggdist::interval_widths(3)
      )
    }
  }

  list(
    "evidence" = if ("evidence" %in% which) {
      yout <- vapply(
        seq_len(nrow(log_evidence)),
        \(i) {
          stats::approx(
            log_volume[min(i, nrow(log_volume)), ],
            exp(log_evidence[i, ]),
            xout = knots,
            rule = 2
          )$y
        },
        double(n)
      )
      safe_curve(knots, yout)
    },
    "weight" = if ("weight" %in% which) {
      yout <- vapply(
        seq_len(nrow(weight)),
        \(i) {
          dens <- ggdist::density_bounded(
            x = log_volume[i, ],
            weights = weight[i, ],
            bounds = c(NA, 0)
          )
          stats::approx(dens$x, dens$y, xout = knots, rule = 2)$y
        },
        double(n)
      )
      safe_curve(knots, yout)
    },
    "likelihood" = if ("likelihood" %in% which) {
      lik_app <- approx(
        colMeans(log_volume),
        lik,
        xout = knots,
        rule = 2
      )
      vctrs::data_frame("x" = lik_app$x, ".value" = lik_app$y)
    }
  )
}

#' Validate Plot Type Argument
#'
#' @param which Character vector: Must be one of "evidence", "weight", or
#' "likelihood".
#' @param call The calling environment.
#'
#' @return Character vector of validated plot types in standard form.
#' @noRd
check_plot_which <- function(which, call = caller_env()) {
  which <- arg_match(
    which,
    values = c("evidence", "weight", "likelihood"),
    multiple = TRUE,
    call = call
  )
  if (length(which) == 0) {
    cli::cli_abort(
      "At least one plot type must be specified in `which`.",
      call = call
    )
  } else if (length(which) > 1) {
    check_required("patchwork", "to combine multiple plots", call = call)
  }
  which
}

# AUTOPLOT METHODS -----

#' Generates a ggplot object for an `ernest_estimate` object containing
#' uncertainty simulations.
#'
#' @param object An `ernest_estimate` object containing uncertainty simulations.
#' @param which Which plots to display.
#' @param call The calling environment for error handling.
#' @param ... Additional arguments passed to the method.
#'
#' @return A ggplot object.
#' @noRd
#' @importFrom ggplot2 autoplot
#' @importFrom posterior draws_of
#' @export
autoplot.ernest_estimate <- function(object, which, ...) {
  diagnostic_data <- summary(object, which = which)
  xint <- attr(object, "dead_log_vol")
  plots <- lapply(which, \(x) {
    switch(
      x,
      "evidence" = autoplot_(
        diagnostic_data[["evidence"]],
        "Evidence",
        xintercept = xint
      ),
      "weight" = autoplot_(
        diagnostic_data[["weight"]],
        "Importance Weight",
        xintercept = xint
      ),
      "likelihood" = autoplot_(
        diagnostic_data[["likelihood"]],
        "Normalized Likelihood",
        xintercept = xint
      )
    )
  })

  if (length(plots) > 1) {
    patchwork::wrap_plots(plots) +
      patchwork::plot_layout(ncol = 1, axes = "collect")
  } else {
    plots[[1]]
  }
}

#' Plot Diagnostic Curve
#'
#' Internal helper used by autoplot to visualize a relationship between
#' a variable and log-volume.
#'
#' @param z_df Data frame of summarized evidence diagnostics.
#' @param xintercept Optional numeric vector of vertical reference lines,
#' typically dead-point log-volumes.
#'
#' @return A `ggplot2::ggplot()` object.
#' @importFrom ggplot2 ggplot aes geom_vline geom_line theme_minimal
#' @importFrom ggplot2 scale_x_continuous scale_y_continuous scale_fill_brewer
#' @noRd
autoplot_ <- function(
  df,
  ylab,
  xintercept = NULL
) {
  p <- ggplot(df, aes(.data$x, y = .data$.value)) +
    scale_x_continuous("Log-volume") +
    scale_y_continuous(ylab) +
    theme_minimal()
  xint <- geom_vline(xintercept = xintercept, linetype = 2)
  if (".width" %in% names(df)) {
    p +
      ggdist::geom_lineribbon(aes(
        y = .data$.value,
        ymin = .data$.lower,
        ymax = .data$.upper
      )) +
      scale_fill_brewer(
        "MHD",
        breaks = ggdist::interval_widths(3),
        labels = ggdist::pretty_widths(3),
        palette = "Reds"
      ) +
      xint
  } else {
    p + geom_line(data = df, aes(y = .data$.value)) + xint
  }
}
