# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

propose_uniform_ <- function(log_lik, prior_transform, num_dim, min_lik, max_attempts) {
    .Call(`_ernest_propose_uniform_`, log_lik, prior_transform, num_dim, min_lik, max_attempts)
}

propose_uniform_cpp <- function(log_lik, prior_transform, num_dim, min_lik, max_attempts) {
    .Call(`_ernest_propose_uniform_cpp`, log_lik, prior_transform, num_dim, min_lik, max_attempts)
}

logaddexp <- function(x, y) {
    .Call(`_ernest_logaddexp`, x, y)
}

