#' @name ernest_sampling
#'
#' @title Specify a likelihood-restricted prior sampler (LRPS)
#'
#' @description
#' Choose a method for replacing the worst point in a live set of possible
#' parameter values.
#'
#' @returns
#' An `ernest_sampling` object, used by [ernest_sampler]
#' during its initialization to create an R environment for its LRPS.
#'
#' @details
#' Nested sampling first generates a set of independently distributed
#' live points within a prior space, then iteratively improves this set through
#' replacing the point with the worst likelihood with a new, improved point. In
#' ernest, the strategies for evolving these points are collectively called
#' likelihood-restricted prior samplers. At present, ernest offers two LRPS:
#' A naive region-based sampler, which randomly samples from the unit cube,
#' and a more sophisticated random walk Metropolis-Hastings sampler, which takes
#' a random point from the live set and walks it through a number of steps.
#'
#' @srrstats {BS1.3b} Documentation on the different sampling
#' algorithms (but warns users away from the inefficient `unif_cube`) sampler.
#' @srrstats {BS4.0} Cites original software implementation.
#'
#' @references `unif_cube` and `rw_walk` are based off of implementations found
#' in the [dynesty](https://dynesty.readthedocs.io/en/v2.1.5/quickstart.html#sampling-options)
#' python package.
NULL

#' @rdname ernest_sampling
#'
#' @description
#' `unif_cube()` is a region-based sampler, where points are generated by
#' sampling uniformly within the unit hypercube, returning a point when
#' a sampled point exceeds  from the prior under a likelihood constraint is to
#' sample randomly from the prior and reject the point if the likelihood
#' constraint is not fulfilled. This method is horribly inefficient in even
#' moderately-large dimensions, but is useful for testing and debugging.
#'
#' @export
unif_cube <- function() {
  new_ernest_sampling(
    parameters = list(),
    name = "Uniform Cube",
    class = uniform_lrps
  )
}

#' @rdname ernest_sampling
#'
#' @description
#' `rwmh_cube` is a MCMC-based sampler, where points are generated by
#' taking random steps within the unit hypercube.
#'
#' @param steps (positive integer) Number of steps to take when generating a
#' proposal point.
#' @param target_acceptance (double between 0 and 1) The target acceptance rate
#' for the sampler.
#'
#' @details
#' When updated during a run (see [nested_sampling()]), the sampler will adjust
#' its step-size to target the specified acceptance rate.
#'
#' @export
rwmh_cube <- function(steps = 25L, target_acceptance = 0.5) {
  new_ernest_sampling(
    parameters = list(steps = steps, target_acceptance = target_acceptance),
    name = "Random Walk Cube",
    class = rwcube_lrps
  )
}

#' Construct a generic ernest_sampling object.
#'
#' @param parameters Named list of control parameters.
#' @param name Name of the sampler.
#' @param class Associated R6 class for the sampler.
#'
#' @noRd
new_ernest_sampling <- function(parameters, name, class) {
  structure(
    list(
      parameters = parameters,
      name = name,
      class = class
    ),
    class = "ernest_sampling"
  )
}
