#' Construct an Ernest Sampler Object
#'
#' @description
#' Creates a new `ernest_sampler` S3 object, which holds the configuration and
#' state for a nested sampling run.
#'
#' @param log_lik_fn An object of class `ernest_likelihood`. The likelihood
#' function for the sampler.
#' @param prior An object of class `ernest_prior`. The
#' prior distribution for the sampler.
#' @param lrps (Optional) An environment
#' containing the sampler implementation. If not provided, will be constructed
#' from `sampling`.
#' @param sampling (Optional) An object of class
#' `ernest_sampling`. The sampler implementation and parameters. Required if
#' `lrps` is not provided.
#' @param n_points Integer. Number of live points to use
#' in the sampler (must be >= 1).
#' @param first_update Integer. Iteration at
#' which to perform the first update (must be >= 0).
#' @param update_interval Integer. Number of iterations between updates
#' (must be >= 0).
#' @param live_points (Optional) An environment for storing live points. If not
#' provided, a new environment is created.
#' @param ... Additional parameters for children of ernest_sampler.
#' @param .class The subclass inheriting from ernest_sampler.
#' @param .call The calling environment.
#' @return An object of class `ernest_sampler`.
#' @note If both `lrps` and `sampling` are provided, `lrps` takes precedence and
#' `prior` is silently ignored.
#' @noRd
new_ernest_sampler <- function(
  log_lik_fn = NULL,
  prior = NULL,
  lrps = NULL,
  sampling = NULL,
  n_points = NULL,
  first_update = NULL,
  update_interval = NULL,
  live_points = NULL,
  ...,
  .class = NULL,
  .call = caller_env()
) {
  check_class(log_lik_fn, "ernest_likelihood", call = .call)
  check_class(prior, "ernest_prior", call = .call)
  check_number_whole(
    n_points,
    min = 1,
    arg = "n_points",
    allow_infinite = FALSE,
    call = .call
  )
  check_number_whole(
    first_update,
    min = 0,
    arg = "first_update",
    allow_infinite = FALSE,
    call = .call
  )
  check_number_whole(
    update_interval,
    min = 0,
    arg = "update_interval",
    allow_infinite = FALSE,
    call = .call
  )
  check_environment(live_points, allow_null = TRUE, call = .call)

  lrps <- if (!is.null(lrps)) {
    check_environment(lrps, arg = "lrps", call = .call)
    lrps
  } else {
    check_class(sampling, "ernest_sampling", call = .call)
    sampling_args <- pairlist2(
      log_lik = log_lik_fn,
      prior_fn = prior$fn,
      n_dim = prior$n_dim,
      !!!sampling$parameters
    )
    eval(call2(sampling$class$new, !!!sampling_args))
  }

  elems <- list(
    log_lik_fn = log_lik_fn,
    prior = prior,
    lrps = lrps,
    n_points = as.integer(n_points),
    first_update = as.integer(first_update),
    update_interval = as.integer(update_interval),
    live_points = live_points %||% new_environment()
  )

  new_elems <- dots_list(..., .homonyms = "error")
  check_unique_names(c(elems, new_elems))

  structure(
    c(elems, new_elems),
    class = c(.class, "ernest_sampler")
  )
}

#' Check an ernest sampler object
#' @param obj An `ernest_sampler` object.
#' @param call The environment from which the function was called.
#' @return `NULL` if the object is valid, otherwise throws an error.
#' @noRd
check_ernest_sampler <- function(obj, call = caller_env()) {
  check_class(obj, "ernest_sampler", call = call)
  check_class(
    obj$log_lik_fn,
    "ernest_likelihood",
    arg = "log_lik_fn",
    call = call
  )
  check_class(obj$prior, "ernest_prior", arg = "prior", call = call)
  check_environment(obj$lrps, arg = "lrps", call = call)
  check_number_whole(
    obj$n_points,
    min = 1,
    arg = "n_points",
    allow_infinite = FALSE,
    call = call
  )
  check_number_whole(
    obj$first_update,
    min = 0,
    arg = "first_update",
    allow_infinite = FALSE,
    call = call
  )
  check_number_whole(
    obj$update_interval,
    min = 0,
    arg = "update_interval",
    allow_infinite = FALSE,
    call = call
  )
  check_environment(obj$live_points, arg = "live_points", call = call)
  invisible(NULL)
}

#' Refresh a sampler to detect validity issues
#' @param x An `ernest_sampler` object.
#' @return An `ernest_sampler` generated by recalling the constructor
#' @noRd
refresh_ernest_sampler <- function(x) {
  do.call(new_ernest_sampler, as.list(x))
}

#' Format method for `ernest_sampler`
#' @param x An `ernest_sampler` object.
#' @param ... Additional arguments (not used).
#' @return A character vector representing the `ernest_sampler` object.
#' @export
#' @noRd
format.ernest_sampler <- function(x, ...) {
  check_ernest_sampler(x)
  cli::cli_format_method({
    str <- glue::glue("{x$n_points} points, {x$prior$n_dim} variables")
    cli::cli_text("An {.cls ernest_sampler}: {str}.")
  })
}

#' Print method for `ernest_sampler`
#' @param x An `ernest_sampler` object.
#' @param ... Additional arguments (not used).
#' @returns `x` invisibly.
#' @export
#' @noRd
print.ernest_sampler <- function(x, ...) {
  cat(format(x, ...), "\n")
  invisible(x)
}
