#' Construct an Ernest Sampler Object
#'
#' Creates a new `ernest_sampler` S3 object, which holds the configuration and
#' state for a nested sampling run.
#'
#' @param log_lik_fn An object of class `ernest_likelihood`. The likelihood
#' function for the sampler.
#' @param prior An object of class `ernest_prior`. The prior distribution for
#' the sampler.
#' @param lrps (Optional) An object of class `ernest_lrps`.
#' @param n_points Integer. Number of live points to use in the sampler.
#' @param first_update Integer. Iteration at which to perform the first update.
#' @param update_interval Integer. Number of iterations between updates.
#' @param run_env (Optional) An environment for storing live points. If not
#' provided, a new environment is created.
#' @param ... Additional parameters for children of ernest_sampler.
#' @param .class The subclass inheriting from ernest_sampler.
#' @param .call The calling environment.
#'
#' @srrstats {G2.4, G2.4a, G2.4b} Explicit conversion of inputs to expected
#' types or error messages for univariate inputs.
#'
#' @return An object of class `ernest_sampler`.
#' @noRd
new_ernest_sampler <- function(
  log_lik_fn = NULL,
  prior = NULL,
  lrps = NULL,
  n_points = NULL,
  first_update = NULL,
  update_interval = NULL,
  run_env = NULL,
  seed = NULL,
  ...,
  .class = NULL,
  .call = caller_env()
) {
  check_class(log_lik_fn, "ernest_likelihood", call = .call)
  check_class(prior, "ernest_prior", call = .call)
  check_class(lrps, "ernest_lrps", call = .call)
  check_number_whole(
    n_points,
    min = 1,
    arg = "n_points",
    allow_infinite = FALSE,
    call = .call
  )
  check_number_whole(
    first_update,
    min = 0,
    arg = "first_update",
    allow_infinite = FALSE,
    call = .call
  )
  check_number_whole(
    update_interval,
    min = 0,
    arg = "update_interval",
    allow_infinite = FALSE,
    call = .call
  )
  check_environment(run_env, allow_null = TRUE, call = .call)
  check_number_whole(seed, min = 1, allow_null = TRUE, call = .call)
  if (is.null(seed)) {
    seed <- sample.int(.Machine$integer.max, 1L)
  }

  unit <- NULL
  log_lik <- NULL
  lrps$unit_log_fn <- rlang::new_function(
    exprs(unit = ),
    expr(log_lik(prior(unit))),
    env = list2env(
      list(log_lik = log_lik_fn, prior = prior$fn),
      parent = globalenv()
    )
  )
  lrps$n_dim <- attr(prior, "n_dim")
  if (is_environment(lrps$cache)) {
    env_unbind(lrps$cache, env_names(lrps$cache))
  }
  lrps <- update_lrps(lrps, ...)

  elems <- list(
    log_lik_fn = log_lik_fn,
    prior = prior,
    lrps = lrps,
    n_points = as.integer(n_points),
    first_update = as.integer(first_update),
    update_interval = as.integer(update_interval),
    run_env = run_env %||% new_environment()
  )

  new_elems <- dots_list(..., .homonyms = "error")
  check_unique_names(c(elems, new_elems))

  obj <- structure(
    c(elems, new_elems),
    seed = as.integer(seed),
    class = c(.class, "ernest_sampler")
  )
  obj
}

#' Reconstruct an `ernest_sampler` object to ensure its validity.
#'
#' @param x An `ernest_sampler` object.
#'
#' @returns An `ernest_sampler` generated by recalling the constructor.
#' @noRd
refresh_ernest_sampler <- function(x) {
  do.call(new_ernest_sampler, c(as.list(x), "seed" = attr(x, "seed")))
}

#' @export
#' @noRd
format.ernest_sampler <- function(x, ...) {
  cli::cli_format_method({
    cli::cli_text("nested sampling specification {.cls ernest_sampler}")
    cli::cli_text("No. Points: {x$n_points}")
    cli::cli_h3("Sampling Method")
    cli::cat_print(x$lrps)
  })
}

#' @export
#' @noRd
print.ernest_sampler <- function(x, ...) {
  cat(format(x, ...), sep = "\n")
  invisible(x)
}
