#' Construct an Ernest Sampler Object
#'
#' Creates a new `ernest_sampler` S3 object, which holds the configuration and
#' state for a nested sampling run.
#'
#' @param log_lik_fn An object of class `ernest_likelihood`. The likelihood
#' function for the sampler.
#' @param prior An object of class `ernest_prior`. The prior distribution for
#' the sampler.
#' @param lrps (Optional) An object of class `ernest_lrps`.
#' @param nlive  Number of points in the live set.
#' @param refresh_frac Fractional reduction in volume before performing updates.
#' @param live_env (Optional) An environment for storing the live set. If not
#' provided, a new environment is created.
#' @param seed  An optional random seed for reproducibility.
#' @param ... Additional parameters for children of ernest_sampler.
#' @param .class The subclass inheriting from ernest_sampler.
#' @param .call The calling environment.
#'
#' @srrstats {G2.4, G2.4a, G2.4b} Explicit conversion of inputs to expected
#' types or error messages for univariate inputs.
#'
#' @return An object of class `ernest_sampler`.
#' @noRd
new_ernest_sampler <- function(
  log_lik_fn = NULL,
  prior = NULL,
  lrps = NULL,
  nlive = NULL,
  refresh_frac = NULL,
  live_env = NULL,
  seed = NA_integer_,
  ...,
  .class = NULL,
  .call = caller_env()
) {
  check_class(log_lik_fn, "ernest_likelihood", call = .call)
  check_class(prior, "ernest_prior", call = .call)
  check_class(lrps, "ernest_lrps", call = .call)
  check_number_whole(
    nlive,
    min = 1,
    arg = "nlive",
    allow_infinite = FALSE,
    call = .call
  )
  check_number_decimal(
    refresh_frac,
    min = 0,
    max = 1,
    arg = "refresh_frac",
    call = .call
  )
  check_environment(live_env, allow_null = TRUE, call = .call)
  check_number_whole(seed, min = 1, allow_na = TRUE, call = .call)

  unit <- NULL
  log_lik <- NULL
  lrps$unit_log_fn <- rlang::new_function(
    exprs(unit = ),
    expr(log_lik(prior(unit))),
    env = list2env(
      list(log_lik = log_lik_fn, prior = prior$fn),
      parent = globalenv()
    )
  )
  lrps$nvar <- attr(prior, "nvar")
  if (is_environment(lrps$cache)) {
    env_unbind(lrps$cache, env_names(lrps$cache))
  }
  lrps <- update_lrps(lrps, ...)

  elems <- list(
    log_lik_fn = log_lik_fn,
    prior = prior,
    lrps = lrps,
    nlive = as.integer(nlive),
    refresh_frac = as.numeric(refresh_frac),
    live_env = live_env %||% new_environment()
  )

  new_elems <- dots_list(..., .homonyms = "error")
  vctrs::vec_names2(c(elems, new_elems), repair = "check_unique")
  obj <- structure(
    c(elems, new_elems),
    seed = as.integer(seed),
    class = c(.class, "ernest_sampler")
  )
  obj
}

#' Reconstruct an `ernest_sampler` object to ensure its validity.
#'
#' @param x An `ernest_sampler` object.
#'
#' @returns An `ernest_sampler` generated by recalling the constructor.
#' @noRd
refresh_ernest_sampler <- function(x) {
  do.call(new_ernest_sampler, c(as.list(x), "seed" = attr(x, "seed")))
}

#' @export
#' @noRd
print.ernest_sampler <- function(x, ...) {
  cli::cli_text("Nested sampling run specification:")
  cli::cli_bullets(c(
    "* No. points: {x$nlive}",
    "* Sampling method: {format(x$lrps, ...)}",
    "* Prior: {format(x$prior, ...)}"
  ))
  invisible(x)
}
